#!/bin/sh

# Abort if any command returns an error value
set -e

case "$1" in
        configure)
        if [ "centreon-engine" != "root" ]; then
                if ! $(grep -E "^centreon-engine:" /etc/group > /dev/null ) ; then
                groupadd -f "centreon-engine"
                fi
        fi

        if [ "centreon-engine" != "root" ]; then
                if ! $(grep -E "^centreon-engine:" /etc/passwd > /dev/null ) ; then
                useradd -d "/var/lib/centreon-engine" -M -r -c "Centreon-engine Admin" -g "centreon-engine" -s /bin/bash "centreon-engine"
                fi
        fi

       if [ -f "/lib/systemd/system/centreon-nrpe3.service" ]; then
                systemctl daemon-reload
                systemctl enable centreon-nrpe3.service
        fi
        ;;

        abort-upgrade|abort-remove|abort-deconfigure)
        ;;

        *)
        echo "$0: called with unknown argument" 1>&2
        exit 0
        ;;
esac

exit 0
